import Head from "next/head";
import styles from "./Home.module.scss";
import SearchUser from "@/src/components/molecules/SearchUser/SearchUser";
import { useSelector } from "react-redux";
import { RootState } from "@/src/store";
import UserGithub from "@/src/components/atoms/UserGithub/UserGithub";
import RepoUser from "@/src/components/molecules/RepoUser/RepoUser";

export default function Home() {
  const githubStore = useSelector((state: RootState) => state.github);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SearchUser />
        {githubStore.selectedUser && (
          <>
            <div className={styles["selected-user"]}>
              <div className={styles["label-selected"]}>Selected User</div>
              <UserGithub user={githubStore.selectedUser} />
            </div>
            <RepoUser />
          </>
        )}
      </main>
    </>
  );
}
